# Generated by Django 2.2.7 on 2019-11-07 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('size', models.PositiveIntegerField(help_text='in square meter')),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('color', models.TextField()),
                ('sedded_at', models.DateField()),
                ('regional', models.BooleanField()),
                ('type', models.CharField(choices=[('v', 'Vegetable'), ('fr', 'Fruit'), ('fl', 'Flower')], max_length=2)),
                ('quantity', models.PositiveIntegerField()),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hw1_gruber.Garden')),
            ],
        ),
    ]
