# Generated by Django 2.2.7 on 2019-11-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw1_gruber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='sedded_at',
            new_name='seeded_at',
        ),
    ]
