# Generated by Django 2.2.7 on 2019-11-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw1_gruber', '0002_auto_20191107_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.CharField(choices=[('ve', 'Vegetable'), ('fr', 'Fruit'), ('fl', 'Flower')], max_length=2),
        ),
    ]
